// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// InvoicesInvoicesItems invoices invoices items
// swagger:model invoicesInvoicesItems
type InvoicesInvoicesItems struct {

	// customer
	Customer string `json:"customer,omitempty"`

	// services
	Services string `json:"services,omitempty"`

	// total
	Total string `json:"total,omitempty"`
}

// Validate validates this invoices invoices items
func (m *InvoicesInvoicesItems) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InvoicesInvoicesItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InvoicesInvoicesItems) UnmarshalBinary(b []byte) error {
	var res InvoicesInvoicesItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
