// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/go-service/proxy_server/models"
)

// GetClientsOKCode is the HTTP code returned for type GetClientsOK
const GetClientsOKCode int = 200

/*GetClientsOK Client list JSON data

swagger:response getClientsOK
*/
type GetClientsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Clients `json:"body,omitempty"`
}

// NewGetClientsOK creates GetClientsOK with default headers values
func NewGetClientsOK() *GetClientsOK {

	return &GetClientsOK{}
}

// WithPayload adds the payload to the get clients o k response
func (o *GetClientsOK) WithPayload(payload *models.Clients) *GetClientsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get clients o k response
func (o *GetClientsOK) SetPayload(payload *models.Clients) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClientsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetClientsInternalServerErrorCode is the HTTP code returned for type GetClientsInternalServerError
const GetClientsInternalServerErrorCode int = 500

/*GetClientsInternalServerError Internal error

swagger:response getClientsInternalServerError
*/
type GetClientsInternalServerError struct {
}

// NewGetClientsInternalServerError creates GetClientsInternalServerError with default headers values
func NewGetClientsInternalServerError() *GetClientsInternalServerError {

	return &GetClientsInternalServerError{}
}

// WriteResponse to the client
func (o *GetClientsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
