// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/go-service/proxy_server/models"
)

// GetInvoicesOKCode is the HTTP code returned for type GetInvoicesOK
const GetInvoicesOKCode int = 200

/*GetInvoicesOK Invoices JSON data

swagger:response getInvoicesOK
*/
type GetInvoicesOK struct {

	/*
	  In: Body
	*/
	Payload *models.Invoices `json:"body,omitempty"`
}

// NewGetInvoicesOK creates GetInvoicesOK with default headers values
func NewGetInvoicesOK() *GetInvoicesOK {

	return &GetInvoicesOK{}
}

// WithPayload adds the payload to the get invoices o k response
func (o *GetInvoicesOK) WithPayload(payload *models.Invoices) *GetInvoicesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get invoices o k response
func (o *GetInvoicesOK) SetPayload(payload *models.Invoices) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInvoicesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetInvoicesBadRequestCode is the HTTP code returned for type GetInvoicesBadRequest
const GetInvoicesBadRequestCode int = 400

/*GetInvoicesBadRequest Invalid data

swagger:response getInvoicesBadRequest
*/
type GetInvoicesBadRequest struct {

	/*Error message body
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetInvoicesBadRequest creates GetInvoicesBadRequest with default headers values
func NewGetInvoicesBadRequest() *GetInvoicesBadRequest {

	return &GetInvoicesBadRequest{}
}

// WithPayload adds the payload to the get invoices bad request response
func (o *GetInvoicesBadRequest) WithPayload(payload string) *GetInvoicesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get invoices bad request response
func (o *GetInvoicesBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInvoicesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetInvoicesInternalServerErrorCode is the HTTP code returned for type GetInvoicesInternalServerError
const GetInvoicesInternalServerErrorCode int = 500

/*GetInvoicesInternalServerError Internal error

swagger:response getInvoicesInternalServerError
*/
type GetInvoicesInternalServerError struct {
}

// NewGetInvoicesInternalServerError creates GetInvoicesInternalServerError with default headers values
func NewGetInvoicesInternalServerError() *GetInvoicesInternalServerError {

	return &GetInvoicesInternalServerError{}
}

// WriteResponse to the client
func (o *GetInvoicesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
