// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetInvoicesHandlerFunc turns a function with the right signature into a get invoices handler
type GetInvoicesHandlerFunc func(GetInvoicesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetInvoicesHandlerFunc) Handle(params GetInvoicesParams) middleware.Responder {
	return fn(params)
}

// GetInvoicesHandler interface for that can handle valid get invoices params
type GetInvoicesHandler interface {
	Handle(GetInvoicesParams) middleware.Responder
}

// NewGetInvoices creates a new http.Handler for the get invoices operation
func NewGetInvoices(ctx *middleware.Context, handler GetInvoicesHandler) *GetInvoices {
	return &GetInvoices{Context: ctx, Handler: handler}
}

/*GetInvoices swagger:route POST /invoices.json getInvoices

Get invoice by specified client ID

*/
type GetInvoices struct {
	Context *middleware.Context
	Handler GetInvoicesHandler
}

func (o *GetInvoices) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetInvoicesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
