// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetClientsHandlerFunc turns a function with the right signature into a get clients handler
type GetClientsHandlerFunc func(GetClientsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetClientsHandlerFunc) Handle(params GetClientsParams) middleware.Responder {
	return fn(params)
}

// GetClientsHandler interface for that can handle valid get clients params
type GetClientsHandler interface {
	Handle(GetClientsParams) middleware.Responder
}

// NewGetClients creates a new http.Handler for the get clients operation
func NewGetClients(ctx *middleware.Context, handler GetClientsHandler) *GetClients {
	return &GetClients{Context: ctx, Handler: handler}
}

/*GetClients swagger:route GET /clients.json getClients

Get all clients

*/
type GetClients struct {
	Context *middleware.Context
	Handler GetClientsHandler
}

func (o *GetClients) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetClientsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
