// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/go-service/proxy_client/models"
)

// GetClientsReader is a Reader for the GetClients structure.
type GetClientsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetClientsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetClientsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetClientsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetClientsOK creates a GetClientsOK with default headers values
func NewGetClientsOK() *GetClientsOK {
	return &GetClientsOK{}
}

/*GetClientsOK handles this case with default header values.

Client list JSON data
*/
type GetClientsOK struct {
	Payload *models.Clients
}

func (o *GetClientsOK) Error() string {
	return fmt.Sprintf("[GET /clients.json][%d] getClientsOK  %+v", 200, o.Payload)
}

func (o *GetClientsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Clients)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClientsInternalServerError creates a GetClientsInternalServerError with default headers values
func NewGetClientsInternalServerError() *GetClientsInternalServerError {
	return &GetClientsInternalServerError{}
}

/*GetClientsInternalServerError handles this case with default header values.

Internal error
*/
type GetClientsInternalServerError struct {
}

func (o *GetClientsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /clients.json][%d] getClientsInternalServerError ", 500)
}

func (o *GetClientsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
