// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/go-service/proxy_client/models"
)

// GetInvoicesReader is a Reader for the GetInvoices structure.
type GetInvoicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInvoicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetInvoicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetInvoicesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetInvoicesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetInvoicesOK creates a GetInvoicesOK with default headers values
func NewGetInvoicesOK() *GetInvoicesOK {
	return &GetInvoicesOK{}
}

/*GetInvoicesOK handles this case with default header values.

Invoices JSON data
*/
type GetInvoicesOK struct {
	Payload *models.Invoices
}

func (o *GetInvoicesOK) Error() string {
	return fmt.Sprintf("[POST /invoices.json][%d] getInvoicesOK  %+v", 200, o.Payload)
}

func (o *GetInvoicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Invoices)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInvoicesBadRequest creates a GetInvoicesBadRequest with default headers values
func NewGetInvoicesBadRequest() *GetInvoicesBadRequest {
	return &GetInvoicesBadRequest{}
}

/*GetInvoicesBadRequest handles this case with default header values.

Invalid data
*/
type GetInvoicesBadRequest struct {
	Payload string
}

func (o *GetInvoicesBadRequest) Error() string {
	return fmt.Sprintf("[POST /invoices.json][%d] getInvoicesBadRequest  %+v", 400, o.Payload)
}

func (o *GetInvoicesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInvoicesInternalServerError creates a GetInvoicesInternalServerError with default headers values
func NewGetInvoicesInternalServerError() *GetInvoicesInternalServerError {
	return &GetInvoicesInternalServerError{}
}

/*GetInvoicesInternalServerError handles this case with default header values.

Internal error
*/
type GetInvoicesInternalServerError struct {
}

func (o *GetInvoicesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /invoices.json][%d] getInvoicesInternalServerError ", 500)
}

func (o *GetInvoicesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
